import {parseLibrary,viewCampaign} from './data.mjs';
import {renderEditor} from './editor.mjs';
const $=id=>document.getElementById(id), el=(tag,text)=>{const n=document.createElement(tag);n.textContent=text??'';return n;};
let db=null;
const draftKey='cronicas-library-draft-v2';
function ask(message){return new Promise(resolve=>{const dialog=el('dialog');dialog.append(el('p',message));const yes=el('button','Continuar'),no=el('button','Cancelar');const done=value=>{dialog.close();dialog.remove();resolve(value);};yes.onclick=()=>done(true);no.onclick=()=>done(false);dialog.oncancel=e=>{e.preventDefault();done(false);};dialog.append(no,yes);document.body.append(dialog);dialog.showModal();});}
function persist(){try{localStorage.setItem(draftKey,JSON.stringify(db));return true;}catch{return false;}}
function commit(next){db=next;const saved=persist();const current=$('group').value;options($('group'),db.groups.filter(g=>g.campaignId===$('campaign').value),'Todos os participantes');if(db.groups.some(g=>g.id===current))$('group').value=current;render();$('status').textContent=(saved?'Rascunho guardado neste navegador.':'Rascunho apenas em memória; exporta antes de fechar.')+' '+(db.localChanges?.length||0)+' alterações por reconciliar com o Sheets. Descarrega a cópia e entrega-a ao chat.';}
function options(select,rows,label){select.replaceChildren();if(label){const o=el('option',label);o.value='';select.append(o);}for(const r of rows){const o=el('option',r.title||r.name);o.value=r.id;select.append(o);}}
function section(parent,title,items){const detail=el('details');detail.append(el('summary',title));if(!items.length)detail.append(el('p','Sem registos.'));for(const text of items)detail.append(el('p',text));parent.append(detail);}
function render(){
 if(!db.campaigns.length){$('content').hidden=true;$('empty').hidden=false;$('title').textContent='Biblioteca sem campanhas';return;}
 const v=viewCampaign(db,$('campaign').value,$('group').value);$('title').textContent=v.campaign.title;$('meta').textContent='Biblioteca: revisão '+db.revision+' · Campanha: revisão '+(v.campaign.revision??'não indicada')+' · Cópia importada do Sheets';$('resume').textContent=[v.campaign.location,v.campaign.worldTime,v.campaign.resume].filter(Boolean).join(' · ');
 for(const id of ['characterList','questList','sessionList','imageList'])$(id).replaceChildren();
 for(const p of v.participants){const card=el('article');card.className='card';card.append(el('h3',p.name),el('small',p.description));const stats=el('div');stats.className='stats';for(const [name,value]of [['PV',p.hp+' / '+p.maxHp],['CA',p.ac],['Nível',p.level]]){const s=el('div');s.className='stat';s.append(el('strong',value),el('span',name));stats.append(s);}card.append(stats);
 card.append(el('p','Atributos: '+['str','dex','con','int','wis','cha'].map(k=>k.toUpperCase()+' '+(p[k]??'?')).join(' · ')));
 card.append(el('p','Dinheiro: '+['cp','sp','ep','gp','pp'].map(k=>k.toUpperCase()+' '+(p[k]===''||p[k]==null?'?':p[k])).join(' · ')));
 card.append(el('p','PV temporários: '+(p.tempHp===''||p.tempHp==null?'?':p.tempHp)+'\nCondições: '+(p.conditions||'Não registadas')+'\nConcentração: '+(p.concentration||'Não registada')+'\nInspiração: '+(p.inspiration||'Não registada')));
 section(card,'Magias',v.spells.filter(r=>r.participantId===p.id).map(r=>r.name+' · '+(r.level===0?'Truque':r.level===''?'Especial / sem nível comum':'Nível '+(r.level??'?'))+' · '+(r.prepared===true?'Preparada':r.prepared===false?'Não preparada':'Preparação não indicada')+'\n'+[r.source,r.ability,r.notes].filter(Boolean).join(' · ')));
 section(card,'Inventário',v.inventory.filter(r=>r.participantId===p.id).map(r=>r.quantity+' × '+r.name+(r.equipped?' · Equipado':'')+(r.notes?'\n'+r.notes:'')));
 section(card,'Recursos e habilidades',v.resources.filter(r=>r.participantId===p.id).map(r=>r.name+': '+r.current+'/'+r.max+' · '+r.recovery+'\n'+(r.notes||'')));
 section(card,'Identidade e detalhes',[p.appearance,p.backstory,p.skills,p.features,p.notes,p.verifiedAt?'Dados verificados em '+p.verifiedAt:''].filter(Boolean));$('characterList').append(card);}
 if(!v.participants.length)$('characterList').append(el('p','Nenhum membro neste grupo.'));
 for(const q of v.quests){const c=el('article');c.className='card';c.append(el('h3',q.title),el('small',q.status),el('p',q.notes));$('questList').append(c);}
 for(const s of v.sessions){const c=el('article');c.className='card';c.append(el('small',s.date+' · '+s.id),el('p',s.summary),el('p',s.changes),el('p',s.resume));$('sessionList').append(c);}
 for(const im of v.images){const c=el('article');c.className='card';c.append(el('h3',im.caption||'Imagem'),el('small',im.createdAt));if(typeof im.fileId==='string'&&/^[A-Za-z0-9_-]+$/.test(im.fileId)){const a=el('a','Abrir imagem privada no Drive');a.href='https://drive.google.com/file/d/'+encodeURIComponent(im.fileId)+'/view';a.target='_blank';a.rel='noopener noreferrer';c.append(a);}else c.append(el('p','Ficheiro ainda não guardado.'));$('imageList').append(c);}
 for(const [id,rows]of [['questList',v.quests],['sessionList',v.sessions],['imageList',v.images]])if(!rows.length)$(id).append(el('p','Sem registos.'));
 $('noteText').textContent=v.campaign.notes||'';$('content').hidden=false;$('empty').hidden=true;
 renderEditor(db,v,commit,message=>$('status').textContent=message);
}
function selectCampaign(){options($('group'),db.groups.filter(g=>g.campaignId===$('campaign').value),'Todos os participantes');render();}
async function load(text){try{const next=parseLibrary(text);if(db&&!await ask('Substituir a biblioteca e o rascunho? Exporta primeiro se tens alterações por guardar.'))return;db=next;options($('campaign'),db.campaigns);$('selectors').hidden=false;selectCampaign();$('export').disabled=false;$('clear').disabled=false;$('paste').value='';$('status').textContent='Biblioteca carregada. '+(persist()?'Cópia guardada neste navegador.':'Apenas em memória.')+' Nenhum dado foi enviado para a rede.';}catch(e){$('status').textContent='Importação recusada: '+e.message+' A biblioteca anterior foi preservada.';}}
$('campaign').onchange=selectCampaign;$('group').onchange=render;$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(f){if(f.size>5000000)throw Error('Limite de 5 MB.');load(await f.text());}}catch(e){$('status').textContent=e.message;}finally{ $('file').value='';}};$('loadPaste').onclick=()=>load($('paste').value);
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='biblioteca.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);$('status').textContent='Download solicitado. O Sheets não foi alterado.';};
$('clear').onclick=async()=>{if(db?.localChanges?.length&&!await ask('Apagar o rascunho deste navegador? Exporta primeiro para preservar alterações.'))return;try{localStorage.removeItem(draftKey);}catch{}db=null;$('content').hidden=true;$('selectors').hidden=true;$('empty').hidden=false;for(const id of ['characterList','questList','sessionList','imageList','noteText','resume'])$(id).replaceChildren();$('campaign').replaceChildren();$('group').replaceChildren();$('title').textContent='As tuas campanhas';$('meta').textContent='Importa biblioteca.json exportado do Sheets.';$('paste').value='';$('export').disabled=true;$('clear').disabled=true;$('status').textContent='Biblioteca removida da memória.';};

try{const saved=localStorage.getItem(draftKey);if(saved){load(saved);$('status').textContent='Rascunho recuperado deste navegador; '+(db?.localChanges?.length||0)+' alterações locais. O Sheets não foi alterado.';}}catch{}
