import {editLibrary,appendRow,membership,appendRoll} from './play.mjs';
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const input=(label,value,type='text')=>{const wrap=el('label',label),n=el('input');n.type=type;n.value=value??'';if(type==='number')n.step='1';wrap.append(n);return {wrap,n};};
const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
const details=(label,parent)=>{const d=el('details');d.append(el('summary',label));parent.append(d);return d;};
const uid=()=>crypto.randomUUID();
let activeTab='party';
export function renderEditor(db,view,commit,status){
 const cid=view.campaign.id,run=fn=>{try{commit(fn());}catch(e){status(e.message);}};
 const old=document.getElementById('playTools');const previous=old?[...old.querySelectorAll('form:first-of-type input, form:first-of-type select')].slice(0,6).map(n=>n.value):null;if(old)old.remove();
 const tools=el('section');tools.id='playTools';document.getElementById('content').prepend(tools);
 const nav=el('nav');nav.className='play-nav';nav.setAttribute('aria-label','Áreas da campanha');tools.append(nav);
 const sections=[...document.querySelectorAll('#content > section')].filter(s=>s!==tools);
 const areas=[['party','Party e fichas'],['quests','Missões'],['sessions','Diário'],['images','Imagens'],['notes','História']];
 const show=key=>{activeTab=key;sections.forEach((s,i)=>s.hidden=areas[i][0]!==key);for(const b of nav.children)b.setAttribute('aria-pressed',String(b.dataset.area===key));};
 for(const [key,label]of areas){const b=button(label,()=>show(key));b.dataset.area=key;nav.append(b);}show(activeTab);
 const dice=details('🎲 Lançar dados',tools);dice.open=true;
 const form=el('form');form.className='form-grid';const actor=el('select');actor.setAttribute('aria-label','Personagem que lança');
 for(const p of view.participants){const o=el('option',p.name);o.value=p.id;actor.append(o);}const actorLabel=el('label','Personagem');actorLabel.append(actor);form.append(actorLabel);
 const count=input('Quantidade',1,'number'),mod=input('Modificador',0,'number'),label=input('Motivo','Lançamento livre');count.n.min=1;count.n.max=30;mod.n.min=-100;mod.n.max=100;
 const sides=el('select'),mode=el('select');sides.setAttribute('aria-label','Dado');mode.setAttribute('aria-label','Modo');
 for(const s of [4,6,8,10,12,20,100]){const o=el('option','d'+s);o.value=s;sides.append(o);}sides.value='20';
 for(const [v,t]of [['normal','Normal'],['advantage','Vantagem'],['disadvantage','Desvantagem']]){const o=el('option',t);o.value=v;mode.append(o);}
 const sl=el('label','Dado'),ml=el('label','Modo');sl.append(sides);ml.append(mode);
 form.append(count.wrap,sl,mod.wrap,ml,label.wrap);const submit=el('button','Lançar dados');submit.type='submit';submit.className='primary';submit.disabled=!view.participants.length;form.append(submit);dice.append(form);
 if(previous&&previous.length===6){const controls=[actor,count.n,sides,mod.n,mode,label.n];controls.forEach((n,i)=>{if(n===actor&&![...actor.options].some(o=>o.value===previous[i]))return;n.value=previous[i];});}
 mode.onchange=()=>{if(mode.value!=='normal'){count.n.value=1;sides.value='20';}};
 form.onsubmit=e=>{e.preventDefault();run(()=>appendRoll(db,cid,actor.value,{count:Number(count.n.value),sides:Number(sides.value),modifier:Number(mod.n.value),mode:mode.value,label:label.n.value.trim().slice(0,150)||'Lançamento livre'}));};
 const history=details('Histórico de dados',dice);const rolls=(db.rolls||[]).filter(r=>r.campaignId===cid&&(!r.participantId||view.participants.some(p=>p.id===r.participantId)));
 if(rolls.length){history.open=false;const last=rolls.at(-1);dice.append(el('p','Último resultado: '+last.total+' · '+last.label));for(const r of rolls.slice(-30).reverse())history.append(el('p',`${db.characters.find(c=>c.id===db.participants.find(p=>p.id===r.participantId)?.characterId)?.name||r.actor||'DM'} · ${r.label}: ${r.total}\n${r.count}d${r.sides} ${r.modifier>=0?'+':''}${r.modifier} · faces [${r.values.join(', ')}] · ${r.mode||'normal'} · ${r.date}`));}else history.append(el('p','Sem rolagens registadas.'));
 dice.append(el('small','O resultado não resolve a ação nem gasta recursos. Partilha a exportação com o DM.'));
 const group=details('Gerir party e combinações',tools),gf=el('form');gf.className='form-grid';const groupName=input('Novo grupo','');groupName.n.required=true;gf.append(groupName.wrap);const gb=el('button','Criar grupo');gf.append(gb);gf.onsubmit=e=>{e.preventDefault();run(()=>appendRow(db,cid,'groups',{id:uid(),campaignId:cid,name:groupName.n.value.trim(),notes:''}));};group.append(gf);
 for(const g of view.groups){const d=details(g.name,group);for(const p of db.participants.filter(p=>p.campaignId===cid)){const l=el('label'),c=el('input');c.type='checkbox';c.checked=db.memberships.some(m=>m.groupId===g.id&&m.participantId===p.id);l.append(c,document.createTextNode(db.characters.find(x=>x.id===p.characterId)?.name||p.id));d.append(l);c.onchange=()=>run(()=>membership(db,cid,g.id,p.id,c.checked));}}
 const cards=[...document.getElementById('characterList').children];
 view.participants.forEach((p,index)=>{
  const card=cards[index],edit=details('Editar ficha de '+p.name,card),f=el('form');f.className='form-grid';const fields=[];
  for(const [key,title]of [['hp','PV atuais'],['maxHp','PV máximos'],['tempHp','PV temporários'],['ac','CA'],['level','Nível'],['gp','Ouro'],['str','Força'],['dex','Destreza'],['con','Constituição'],['int','Inteligência'],['wis','Sabedoria'],['cha','Carisma']]){const x=input(title,p[key],'number');x.n.min=key==='level'?1:0;f.append(x.wrap);fields.push([key,x.n]);}
  for(const [key,title]of [['conditions','Condições'],['concentration','Concentração'],['inspiration','Inspiração'],['notes','Notas']]){const x=input(title,p[key]);f.append(x.wrap);fields.push([key,x.n]);}
  const save=el('button','Guardar ficha no rascunho');save.className='primary';f.append(save);edit.append(f);
  f.onsubmit=e=>{e.preventDefault();run(()=>editLibrary(db,cid,'participants',p.id,Object.fromEntries(fields.map(([k,n])=>[k,n.type==='number'&&n.value!==''?Number(n.value):n.value]))));};
  const quick=el('div');quick.className='actions';quick.append(button('−1 PV',()=>run(()=>editLibrary(db,cid,'participants',p.id,{hp:Math.max(0,p.hp-1)}))),button('+1 PV',()=>run(()=>editLibrary(db,cid,'participants',p.id,{hp:Math.min(p.maxHp,p.hp+1)}))));card.insertBefore(quick,card.children[3]||null);
  const resources=details('Gerir recursos',card);for(const r of view.resources.filter(r=>r.participantId===p.id)){const line=el('div');line.className='resource-line';line.append(el('span',r.name+' · '+r.current+'/'+r.max),button('Gastar',()=>run(()=>editLibrary(db,cid,'resources',r.id,{current:Math.max(0,r.current-1)}))),button('Recuperar 1',()=>run(()=>editLibrary(db,cid,'resources',r.id,{current:Math.min(r.max,r.current+1)}))));resources.append(line);}resources.append(el('small','Recupera apenas quando o descanso ou a regra aplicável o permitir.'));
  const spells=details('Preparar magias',card);for(const s of view.spells.filter(s=>s.participantId===p.id)){if(s.level===0||s.level===''||s.level==null)continue;const l=el('label'),c=el('input');c.type='checkbox';c.checked=s.prepared===true;l.append(c,document.createTextNode(s.name));spells.append(l);c.onchange=()=>run(()=>editLibrary(db,cid,'spells',s.id,{prepared:c.checked}));}spells.append(el('small','Confirma descanso, acesso à magia e limite de preparação com o DM.'));
  const sf=el('form');sf.className='form-grid';const sn=input('Nova magia',''),slv=input('Nível da magia',0,'number'),sd=input('Descrição e acesso','');sn.n.required=true;slv.n.min=0;slv.n.max=9;slv.n.required=true;sf.append(sn.wrap,slv.wrap,sd.wrap,el('button','Registar magia'));spells.append(sf);sf.onsubmit=e=>{e.preventDefault();run(()=>appendRow(db,cid,'spells',{id:uid(),participantId:p.id,name:sn.n.value.trim(),level:Number(slv.n.value),prepared:Number(slv.n.value)===0,source:'Registo do jogador; confirmar aprendizagem com o DM',ability:'',notes:sd.n.value}));};
  const inv=details('Gerir inventário',card);for(const item of view.inventory.filter(x=>x.participantId===p.id)){const f=el('form');f.className='form-grid';const name=input('Objeto',item.name),qty=input('Quantidade',item.quantity,'number'),notes=input('Notas',item.notes);name.n.required=true;qty.n.min=0;qty.n.required=true;const equip=el('label','Equipado'),eq=el('select');for(const [v,t]of [['','Não indicado'],['true','Sim'],['false','Não']]){const o=el('option',t);o.value=v;eq.append(o);}eq.value=item.equipped===''||item.equipped==null?'':String(item.equipped);equip.append(eq);f.append(name.wrap,qty.wrap,notes.wrap,equip,el('button','Atualizar'));inv.append(f);f.onsubmit=e=>{e.preventDefault();run(()=>editLibrary(db,cid,'inventory',item.id,{name:name.n.value.trim(),quantity:Number(qty.n.value),notes:notes.n.value,equipped:eq.value===''?'':eq.value==='true'}));};}
  const add=el('form');add.className='form-grid';const name=input('Novo objeto',''),qty=input('Quantidade',1,'number'),note=input('Notas','');name.n.required=true;qty.n.min=1;qty.n.required=true;add.append(name.wrap,qty.wrap,note.wrap,el('button','Adicionar objeto'));inv.append(add);add.onsubmit=e=>{e.preventDefault();run(()=>appendRow(db,cid,'inventory',{id:uid(),participantId:p.id,name:name.n.value.trim(),quantity:Number(qty.n.value),equipped:'',notes:note.n.value}));};
 });
 const addEntry=details('Acrescentar entrada ao diário',document.getElementById('sessionList')),jf=el('form');jf.className='form-grid';const title=input('Título',''),date=input('Data',new Date().toISOString().slice(0,10),'date'),body=el('textarea');body.setAttribute('aria-label','Texto da entrada');body.required=true;title.n.required=true;jf.append(title.wrap,date.wrap,body,el('button','Guardar entrada'));addEntry.append(jf);jf.onsubmit=e=>{e.preventDefault();run(()=>appendRow(db,cid,'sessions',{id:uid(),campaignId:cid,groupId:document.getElementById('group').value,date:date.n.value,summary:title.n.value+'\n'+body.value,changes:'Entrada local do jogador; validar com o DM.',resume:''}));};
}
